Sergeev
ValentinV95/mp2-2023-lab4-polinoms pull request #1
Opened 2024-02-03 17:36 UTC by maksimus-sergeyev

2024-02-03 17:39 UTC, maksimus-sergeyev commented
@NeiroYT, @KorotinEgor можете проверять.

2024-02-07 18:06 UTC, NeiroYT requested changes

2024-02-07 18:06 UTC, NeiroYT commented on src/polynom.cpp
> +}
```suggestion
    if (deg >= max_degree * max_degree * max_degree) throw std::exception("too large degree"); 
}
```

2024-02-07 18:06 UTC, NeiroYT commented on src/polynom.cpp
> +    if ((deg1 > max_degree) || (deg2 > max_degree) || (deg3 > max_degree)) throw std::exception("too large degree");
```suggestion
    if ((deg1 >= max_degree) || (deg2 >= max_degree) || (deg3 >= max_degree)) throw std::exception("too large degree");
```

2024-02-07 18:06 UTC, NeiroYT commented on src/polynom.cpp
> +                throw std::exception("too large degree");
не проверяется ли всё это и так в функции `add_monom()`?

2024-02-07 18:06 UTC, NeiroYT commented on src/polynom.cpp
> +Polynom& Polynom::operator=(const Polynom& p) { if (this != &p) polynom = p.polynom; return *this; }
self assigment already checked in operator= of list

2024-02-07 18:06 UTC, NeiroYT commented on src/polynom.cpp
> +                throw std::exception("too large degree");
всё, понял идею

2024-02-07 18:11 UTC, NeiroYT commented on src/polynom.cpp
> +void Polynom::add_monom(double coef, unsigned short deg)
O(n^2) worst-case when adding n monoms

2024-02-08 07:41 UTC, maksimus-sergeyev commented on src/polynom.cpp
> +void Polynom::add_monom(double coef, unsigned short deg)
где ты квадрат нашел? тут ровно 2N проверок и переходов, быстрее сделать нельзя в односвязном списке

2024-02-08 07:43 UTC, maksimus-sergeyev commented on src/polynom.cpp
> +Polynom& Polynom::operator=(const Polynom& p) { if (this != &p) polynom = p.polynom; return *this; }
классы должны быть абстрактными и не зависеть от реализации друг от друга, поэтому такие ошибки обязаны проверяться

2024-02-08 08:02 UTC, NeiroYT commented on src/polynom.cpp
> +void Polynom::add_monom(double coef, unsigned short deg)
это для вставки одного монома О(N)?

2024-02-08 15:16 UTC, maksimus-sergeyev commented on src/polynom.cpp
> +void Polynom::add_monom(double coef, unsigned short deg)
со всей возможной очевидностью

2024-02-11 09:43 UTC, KorotinEgor commented on src/polynom.cpp
> +}
Я уж хотел сказать, что код идеален и не к чему придираться, но теперь:
А что если (*iter).coefficient * coef окажется < eps?

2024-02-11 12:04 UTC, maksimus-sergeyev commented on src/polynom.cpp
> +}
вот же пристал... делать нечего что ль? иди лучше у себя переработай ввод и вывод полинома, для общего случая, когда степень не одна цифра

2024-02-11 12:56 UTC, KorotinEgor commented on src/polynom.cpp
> +}
а это вообще как связано? к тому же вывод и так работает в общем случае

2024-04-04 08:31 UTC, ValentinV95 reviewed
Лабораторная принята.
Основное замечание это разделение обязаностей между полиномом и листом и кто отвечает за отсортированность (обсуждалось на паре)

2024-04-10 10:53 UTC, closed without merging